- id: arxiv:2512.03701
  type: paper
  description: >
    Structured Uncertainty Similarity Score (SUSS): Learning a Probabilistic,
    Interpretable, Perceptual Metric Between Images.
  date: 2025
  link: https://lopasole02.github.io/SUSS/
  image: images/publications/suss_fig1.png
  doi: 10.48550/arXiv.2512.03701
  tags:
    - Computer Vision
    - Machine Learning
  repo: lopasole02/Structured-Uncertainty-Similarity-Score
